/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 keyboard_animated.gltf 
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/keyboard_animated.gltf");
  const { actions } = useAnimations(animations, group);
  const [hovered, setHovered] = useState(false);
  useEffect(
    () => void (document.body.style.cursor = hovered ? "pointer" : "auto"),
    [hovered]
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          castShadow
          receiveShadow
          name="cord"
          geometry={nodes.cord.geometry}
          material={materials.darkgrey}
        />
        <mesh
          castShadow
          receiveShadow
          name="body"
          geometry={nodes.body.geometry}
          material={materials.yellow}
        />
        <mesh
          castShadow
          receiveShadow
          name="bottom"
          geometry={nodes.bottom.geometry}
          material={materials.darkgrey}
        />
        <mesh
          castShadow
          receiveShadow
          name="cap"
          geometry={nodes.cap.geometry}
          material={materials.powerbank_grey}
        />
        <group name="plug">
          <mesh
            castShadow
            receiveShadow
            name="Cube015"
            geometry={nodes.Cube015.geometry}
            material={materials.darkgrey}
          />
          <mesh
            castShadow
            receiveShadow
            name="Cube015_1"
            geometry={nodes.Cube015_1.geometry}
            material={materials.purple}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          name="plug_rim"
          geometry={nodes.plug_rim.geometry}
          material={materials.darkgrey}
        />
        <group name="cord_rim">
          <mesh
            castShadow
            receiveShadow
            name="Circle003"
            geometry={nodes.Circle003.geometry}
            material={materials.purple}
          />
          <mesh
            castShadow
            receiveShadow
            name="Circle003_1"
            geometry={nodes.Circle003_1.geometry}
            material={materials.darkgrey}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          name="key_logo"
          geometry={nodes.key_logo.geometry}
          material={materials.logo_txtr}
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
          onClick={() => {
            actions["key_logoAction"].setLoop(THREE.LoopOnce).play().reset();
          }}
        />
        <mesh
          castShadow
          receiveShadow
          name="key_long"
          geometry={nodes.key_long.geometry}
          material={materials.logoText_txtr}
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
          onClick={() => {
            actions["key_longAction"].setLoop(THREE.LoopOnce).play().reset();
          }}
        />
        <mesh
          castShadow
          receiveShadow
          name="key_middle_left"
          geometry={nodes.key_middle_left.geometry}
          material={materials.nfc_txtr}
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
        />
        <mesh
          castShadow
          receiveShadow
          name="key_middle_middle"
          geometry={nodes.key_middle_middle.geometry}
          material={materials.bitcoin_txtr}
          onPointerOver={() => setHovered(true)}
          onPointerOut={() => setHovered(false)}
        />
        <mesh
          castShadow
          receiveShadow
          name="key_middle_right"
          geometry={nodes.key_middle_right.geometry}
          material={materials.tickets_txtr}
        />
        <mesh
          castShadow
          receiveShadow
          name="key_upper_left"
          geometry={nodes.key_upper_left.geometry}
          material={materials.ruble_txtr}
          onClick={() => {
            actions["key_upper_leftAction"]
              .setLoop(THREE.LoopOnce)
              .play()
              .reset();
          }}
        />
        <mesh
          castShadow
          receiveShadow
          name="key_upper_middle"
          geometry={nodes.key_upper_middle.geometry}
          material={materials.like_txtr}
        />
        <mesh
          castShadow
          receiveShadow
          name="key_upper_right"
          geometry={nodes.key_upper_right.geometry}
          material={materials.euro_txtr}
        />
        <mesh
          castShadow
          receiveShadow
          name="base_inner"
          geometry={nodes.base_inner.geometry}
          material={materials.purple}
        />
        <mesh
          castShadow
          receiveShadow
          name="base_outer"
          geometry={nodes.base_outer.geometry}
          material={materials.darkgrey}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/keyboard_animated.gltf");
